### PR TITLE
Upgrade

### PR DESCRIPTION
**Pull request by pepa65**
I put this in a 'feature' branch for review. This should provide a more convenient upgrade of existing installs, more flexibility to control the installed location and allow for binaries outside of PATH.

### CODE REVIEW

**Comment by pepa65** [comment]
Sorry, not sure how this got suddenly merged to your master. I though I was merging my latest commit to my other commits...

**Review by mholt — COMMENTED** [review]
I'd like this to be reverted. I don't want a full list of the features enumerated, as they will be changing rapidly. Please submit PR to revert @pepa65 - thanks.

**Comment by pepa65** [comment]
Can you provide an automated way to access the valid features that the download URL allows??

**Comment by mholt** [comment]
Eventually perhaps -- but this bash script is not the place for it.

**Pull request merged**
