### PR TITLE
Incorporate MinGW and MSYS2 detection from pull #24

### PR DESCRIPTION
**Pull request by pepa65**
After suggestion from https://github.com/caddyserver/getcaddy.com/pull/24

### CODE REVIEW

**Comment by mholt** [comment]
@pepa65 Thanks; I merged #24 - after this is synced up I can merge and deploy this.

**Comment by pepa65** [comment]
Any suggestions how this long mess of commits can be cleaned up??
Anyway, the relevant fix is https://github.com/caddyserver/getcaddy.com/pull/25/commits/9e6408d62163fc3dd6568df34fb80e5c04882e7f for the "setcap not found on Debian issue".

**Comment by mholt** [comment]
Hmm, in this case the change is simple enough, I'd just branch off the latest master again and make the change and immediately commit and push. You can squash the commit and force push to your branch to get rid of all the extra cruft in this PR.

**Comment by pepa65** [comment]
I am afraid that goes beyond my git-fu... Should I just erase my repo and reclone afresh?

**Comment by mholt** [comment]
Check out the latest on master, make a new branch from that, make your change, commit it, then force push to this branch (--force). You can google it. :) Or whatever you want is fine, frankly.

**Comment by pepa65** [comment]
If you're not too bothered, I'll leave it. I tried checking out the latest, making a new branch, but found that it already had the change...

**Pull request merged**
