### PR TITLE
Uppercase translation using external tool tr for bash<4

### PR DESCRIPTION
**Pull request by pepa65**
Fixing https://forum.caddyserver.com/t/getcaddy-com-bash-script-gives-an-error/1258

### CODE REVIEW

**Comment by mholt** [comment]
Awesome!! Thanks. I'll make you a collaborator on the repo too, so you can work in a branch instead of a fork. :)

**Comment by pepa65** [comment]
Does that mean I should get rid of my fork and make a clone of this one?

**Comment by mholt** [comment]
No, you can still use your fork if you want.

**Comment by pepa65** [comment]
So I would do the same thing, submit a pull request, and then I can approve it myself? Or is there a better way??

**Comment by mholt** [comment]
This repo is kind of on the sideline so there aren't many contributors to it, but I usually like to have one other collaborator (doesn't have to be me) review changes. So for now just keep doing PRs and if somebody else (qualified) approves the change, then it can be merged. :+1:

**Pull request merged**
