### PR TITLE
Only save 1 unversioned backup

### PR DESCRIPTION
**Pull request by pepa65**
Still no idea how to get rid of all the other commits. If I start afresh, I'm sure it will accumulate again. There must be a more sane way to do this...

### CODE REVIEW

**Comment by mholt** [comment]
What's your git flow? Usually a checkout of the branch at the latest commit, make a new commit, and then a pull request should simply show the new commit...

**Comment by pepa65** [comment]
What I've been doing (after the fork) is commit changes, push them, and then creating a pull request. And again, and again...

**Comment by mholt** [comment]
Oh yeah, I just noticed you're merging from your fork. You have push rights to the repository, you know. That should be easier than working in a fork if you don't want to!

GitHub says your fork is 23 commits ahead of this repo... somehow. So I'd say maybe your fork's commit history is messed up? https://github.com/caddyserver/getcaddy.com/compare/master...pepa65:master - are you pulling in the changes from this repo?

**Comment by pepa65** [comment]
Any idea how to clean up a messed up commit history?? Yes, I was using pepa65/getcaddy.com/master

OK, I will use the main repository from now on; I thought you had said you preferred I not use the main repo, but since checks are in place, it's fairly safe. And then it still needs to be pushed out to the webserver, right?

**Comment by mholt** [comment]
@pepa65 Yes, the deploys to getcaddy.com are done by me. You can always safely work in a branch on this repo! It's the master branch that's protected.

Go ahead and clean up this PR and then I'll look into merging it. :+1: Thank you!

**Comment by pepa65** [comment]
OK, I'll cancel this one and branch from the main master.

**Pull request closed without merging**
