### PR TITLE
Add more keyservers to fix issue #38

### PR DESCRIPTION
**Pull request by pepa65**
As discussed.

### CODE REVIEW

**Comment by mholt** [comment]
Cool, you're fast as always, thank you! Does it work (did you try it once or twice)? :smile:

**Comment by pepa65** [comment]
Yes, I tried it. If you fill in non-keyservers they won't work of course, and if they all don't work, the binary can't be verified, but then there's no error. And if at least one of them works, the binary gets verified.

**Review by mholt — APPROVED** [review]
LGTM. Thank you again!!

**Comment by mholt** [comment]
@pepa65 Just FYI I'll be releasing this sometime soon this week with a few changes of my own. Stay tuned!

**Pull request merged**
